### ISSUE TITLE
I can't use it

### ISSUE THREAD

**Issue by BarryYangi** [alexmarqs/spotify-now-playing-svg#1]
Why can't I use it on Vercel after successfully deploying following the steps in the documentation?
![image](https://github.com/alexmarqs/spotify-now-playing-svg/assets/73282988/6278cdc1-0f43-4307-aa03-c5baa624dcad)

**Comment by BarryYangi** [comment]
When I debug locally, I encounter the following error:
```
Error: Cannot use import statement outside a module
```

**Comment by alexmarqs** [comment]
hey @BarryYangi can you send me / paste the server logs, so I can try to help you!

**Comment by BarryYangi** [comment]
![image](https://github.com/alexmarqs/spotify-now-playing-svg/assets/73282988/ba6a9dbd-5858-4979-8881-cefac3b188cd)

the vercel runtime logs just like this when I visit /api

**Comment by alexmarqs** [comment]
Hey @BarryYangi just tested it and for Node 14 and Node 16 seems to be working. I switched the function to use Node 18 (via vercel project settings -> note that you need to redeploy to take effect) and I was also having the issue "Error: Cannot use import statement outside a module". 

I fixed that forcing the module ts config to be commonjs (check my latest commit). There are other workarounds like changing the vercel cli version or just use ESM as mentioned https://github.com/orgs/vercel/discussions/1225. Let me know if it solved the issue!

**Comment by BarryYangi** [comment]
This issue has been resolved. I believe I tried adjusting this value before, but it seemed to fail last time. Fortunately, it's now fixed. Thank you! Additionally, I think this idea is fantastic!

**Comment by alexmarqs** [comment]
@BarryYangi good that this is useful for you! btw, if you like it don't forget the repo star ⭐ 😄 , maybe I will refactor this soon (to use api route handlers from next.js 13 for example) , let's see.
